"""Q1 2027 title roster from Scheduling PDF — personal clay only.

Exact Confluence dates are NOT auto-recomputed; they are stored as-is
when seeded so holiday slips and exclusivity edits stay true.
Recompute only if Hands unlocks + asks.
"""

from __future__ import annotations

from typing import Any

# Minimal fields for seed; server fills phases from paste tables below
# or leaves release_date for reverse calc.

Q1_2027_TITLES: list[dict[str, Any]] = [
    {
        "code": "BSG-Q1G1-2027",
        "name": "The Castaway",
        "subtitle": "TakeThe Bank + Le Bandit",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "Castaway / tropical",
        "math_model": "TakeThe Bank + Le Bandit",
        "release_date": "2027-01-07",
        "quarter": "Q1 2027",
        "notes": "MEDIUM · full math path",
    },
    {
        "code": "BSG-Q1G2-2027",
        "name": "Love Potion #9",
        "subtitle": "3 Pots of Olympus 1:2",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "Love Potion",
        "math_model": "3 Pots of Olympus 1:2",
        "release_date": "2027-01-21",
        "quarter": "Q1 2027",
        "notes": "MEDIUM · LQA holiday +1w · rollout shifted for Dev holidays",
    },
    {
        "code": "NG-Q1G1-2027",
        "name": "3 Pot Buffalo (TMP)",
        "subtitle": "3 Pots of Olympus EXTRA-DOUBLE-MULTI",
        "product_line_id": "line-ng",
        "complexity": "math_clone",
        "status": "active",
        "theme": "Buffalo / 3 Pot",
        "math_model": "Math clone — specs not required",
        "release_date": "2027-01-11",
        "quarter": "Q1 2027",
        "notes": "NG nucleus · rebranded as BSG THE Streamer",
        "twin_code": "BSG-RE-STREAMER-Q1G1",
        "bsg_twin": "THE Streamer",
        "bsg_release_date": "2027-02-04",
    },
    {
        "code": "BSG-RE-STREAMER-Q1G1",
        "name": "THE Streamer",
        "subtitle": "Betsoft rebrand of NG 3 Pot Buffalo",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "planned",
        "kind": "rebrand",
        "theme": "Buffalo / 3 Pot (logo swap)",
        "math_model": "Same as NG nucleus — new logo only",
        "release_date": "2027-02-04",
        "quarter": "Q1 2027",
        "notes": "REBRAND · thin date set after NG ships",
        "nucleus_code": "NG-Q1G1-2027",
        "rebrand_of": "NG-Q1G1-2027",
        "twin_code": "NG-Q1G1-2027",
    },
    {
        "code": "BSG-Q1G3-2027",
        "name": "4 Tech Bros",
        "subtitle": "4 Pots of Riches 1:2",
        "product_line_id": "line-bsg",
        "complexity": "complex",
        "status": "active",
        "theme": "Tech Bros",
        "math_model": "4 Pots of Riches 1:2",
        "release_date": "2027-01-28",
        "quarter": "Q1 2027",
        "notes": "COMPLEX · 14w dev · exclusivity shortened for math prep",
    },
    {
        "code": "BSG-Q1G4-2027",
        "name": "THE Director",
        "subtitle": "1:1 Huff'n'Lots of Puff",
        "product_line_id": "line-bsg",
        "complexity": "complex",
        "status": "active",
        "theme": "Director",
        "math_model": "Huff'n'Lots of Puff 1:1",
        "release_date": "2027-02-11",
        "quarter": "Q1 2027",
        "notes": "COMPLEX · Feb 2027",
    },
    {
        "code": "BSG-Q1G5-2027",
        "name": "THE Final Bell",
        "subtitle": "1:2 Good Girl Bad Girl 2",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "Final Bell",
        "math_model": "Good Girl Bad Girl 2 1:2 · Completed Maths",
        "release_date": "2027-02-18",
        "quarter": "Q1 2027",
        "notes": "MEDIUM",
    },
    {
        "code": "NG-Q1G2-2027",
        "name": "TBC — Spicy Fortunes Theme",
        "subtitle": "The Queen of Social Media (Q3G6Y2025)",
        "product_line_id": "line-ng",
        "complexity": "math_clone",
        "status": "active",
        "theme": "Spicy Fortunes",
        "math_model": "Math clone path",
        "release_date": "2027-02-15",
        "quarter": "Q1 2027",
        "notes": "NG nucleus · BSG rebrand follows",
        "twin_code": "BSG-RE-NGQ1G2",
        "bsg_twin": "Name TBD",
        "bsg_release_date": "2027-03-04",
    },
    {
        "code": "BSG-RE-NGQ1G2",
        "name": "Name TBD (BSG rebrand)",
        "subtitle": "Betsoft rebrand of NG Q1G2 Spicy Fortunes",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "planned",
        "kind": "rebrand",
        "theme": "Spicy Fortunes (logo swap)",
        "math_model": "Same nucleus math",
        "release_date": "2027-03-04",
        "quarter": "Q1 2027",
        "notes": "REBRAND · first Thursday after NG month pattern",
        "nucleus_code": "NG-Q1G2-2027",
        "rebrand_of": "NG-Q1G2-2027",
        "twin_code": "NG-Q1G2-2027",
    },
    {
        "code": "BSG-Q1G6-2027",
        "name": "TBC — Diamonds/777 Theme",
        "subtitle": "1:2 Thunder Coins XXL",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "Diamonds / 777",
        "math_model": "Thunder Coins XXL 1:2",
        "release_date": "2027-02-25",
        "quarter": "Q1 2027",
        "notes": "MEDIUM · exclusivity removed for math prep",
    },
    {
        "code": "BSG-Q1G7-2027",
        "name": "Ultimate Golden Dragon Inferno 1000",
        "subtitle": "Fortune Gems 500",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "Golden Dragon Inferno",
        "math_model": "Fortune Gems 500",
        "release_date": "2027-03-11",
        "quarter": "Q1 2027",
        "notes": "MEDIUM · March",
    },
    {
        "code": "BSG-Q1G8-2027",
        "name": "THE 3 Karens",
        "subtitle": "The Aristocrat COLLECT-MULTI-DOUBLE + shorter bonus cycle",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "3 Karens",
        "math_model": "Aristocrat collect-multi-double · Completed Maths",
        "release_date": "2027-03-18",
        "quarter": "Q1 2027",
        "notes": "MEDIUM",
    },
    {
        "code": "NG-Q1G3-2027",
        "name": "Name TBD",
        "subtitle": "TBD math",
        "product_line_id": "line-ng",
        "complexity": "medium",
        "status": "active",
        "theme": "TBD",
        "math_model": "TBD",
        "release_date": "2027-03-01",
        "quarter": "Q1 2027",
        "notes": "NG MEDIUM · Mon release",
    },
    {
        "code": "NG-Q1G4-2027",
        "name": "Name TBD — Firecracker",
        "subtitle": "5 Pot BAO ZHU ZHAO FU FIRECRACKER EXPRESS 1:1",
        "product_line_id": "line-ng",
        "complexity": "medium",
        "status": "active",
        "theme": "Firecracker / Bao Zhu",
        "math_model": "5 Pot Firecracker Express 1:1",
        "release_date": "2027-03-29",
        "quarter": "Q1 2027",
        "notes": "NG nucleus · 16w dev · BSG rebrand Apr 1",
        "twin_code": "BSG-RE-NGQ1G4",
        "bsg_twin": "Name TBD",
        "bsg_release_date": "2027-04-01",
    },
    {
        "code": "BSG-RE-NGQ1G4",
        "name": "Name TBD (BSG rebrand · Firecracker)",
        "subtitle": "Betsoft rebrand of NG Q1G4",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "planned",
        "kind": "rebrand",
        "theme": "Firecracker (logo swap)",
        "math_model": "Same nucleus math",
        "release_date": "2027-04-01",
        "quarter": "Q2 2027",
        "notes": "REBRAND · Q2 calendar for BSG ship",
        "nucleus_code": "NG-Q1G4-2027",
        "rebrand_of": "NG-Q1G4-2027",
        "twin_code": "NG-Q1G4-2027",
    },
    {
        "code": "BSG-Q1G9-2027",
        "name": "TBC TITLE",
        "subtitle": "1:2 Le Bandit",
        "product_line_id": "line-bsg",
        "complexity": "medium",
        "status": "active",
        "theme": "TBC",
        "math_model": "Le Bandit 1:2 · Completed Maths",
        "release_date": "2027-03-25",
        "quarter": "Q1 2027",
        "notes": "MEDIUM · exclusivity removed Jun 25 note in PDF",
    },
]
